Repository Monday-Morning/project-reclamation, pull requests merged in 2022-10, with the labels that each got.

#149 fix: get all articles in latest issue
  server/schema/issue/issue.type.js
Labels: bugfix, hacktoberfest

#148 feat(query): get articles by year and month
  server/schema/article/article.datasources.js
  server/schema/article/article.query.js
  server/schema/article/article.resolver.js
Labels: enhancement, hacktoberfest

#147 feat: get list of user by account type
  server/schema/article/article.resolver.js
  server/schema/user/user.datasources.js
  server/schema/user/user.query.js
  server/schema/user/user.resolver.js
Labels: enhancement, hacktoberfest

#150 feat: imagekit auth end point
  server/package.json
  server/router/index.js
  server/yarn.lock
Labels: enhancement, hacktoberfest

#153 feat: auth check endpoint
  server/router/index.js
  server/utils/userAuth/index.js
  server/utils/userAuth/permission.js
Labels: enhancement, wip, hacktoberfest

#154 chore(lint): fix lint issue in article resolve
  server/schema/article/article.resolver.js
Labels: bugfix, hacktoberfest

#151 feat: set and update user role
  server/schema/user/firebaseUser.type.js
  server/schema/user/user.datasources.js
  server/schema/user/user.mutation.js
  server/schema/user/user.query.js
  server/schema/user/user.resolver.js
Labels: enhancement, safe-for-checks, hacktoberfest

#156 feat: count total no of articles
  server/schema/article/article.datasources.js
  server/schema/article/article.query.js
  server/schema/article/article.resolver.js
Labels: enhancement, hacktoberfest

#152 fix: eslint, prettier and setup workflows
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  .github/workflows/setup.yml
  server/env/.env.sample
Labels: bugfix, hacktoberfest
