Repository Monday-Morning/project-reclamation, pull requests merged in 2022-05, with the labels that each got.

#131 feat(article): redirect old links to new links
  server/schema/article/article.datasources.js
  server/schema/article/article.query.js
  server/schema/article/article.resolver.js
  server/schema/article/article.type.js
Labels: enhancement, safe-for-checks

#132 feat: query to count of articles by subcategory
  server/schema/article/article.datasources.js
  server/schema/article/article.query.js
  server/schema/article/article.resolver.js
Labels: enhancement, wip, safe-for-checks

#133 fix: search query index fix
  server/schema/article/article.datasources.js
Labels: enhancement, wip, bugfix, safe-for-checks
