Repository Monday-Morning/project-reclamation, pull requests merged in 2022-11, with the labels that each got.

#157 feat (graphql): add media section
  planning/v1/ROLES.md
  server/schema/index.js
  server/schema/media/media.datasources.js
  server/schema/media/media.mutation.js
  server/schema/media/media.query.js
  server/schema/media/media.resolver.js
  server/schema/media/media.schema.js
  server/schema/media/media.type.js
  server/utils/userAuth/index.js
Labels: enhancement, hacktoberfest

#158 feat: add query for autocomplete suggestions
  server/schema/article/article.datasources.js
  server/schema/article/article.query.js
  server/schema/article/article.resolver.js
Labels: enhancement

#159 lint: fix lint issue in media resolver
  server/schema/media/media.resolver.js
Labels: bugfix

#161 fix: add id fields in aggregation pipeline
  server/schema/article/article.datasources.js
Labels: bugfix

#162 fix: create user permission check
  server/schema/user/user.resolver.js
Labels: bugfix

#160 feat: setup firebase emulator
  .firebaserc
  firebase.json
  firebase/remoteconfig.template.json
  server/config/firebase.js
  server/env/.env.sample
Labels: enhancement

#138 feat(graphQl): add company, live and media
  planning/v1/ROLES.md
  server/config/apolloServer.js
  server/schema/common/image.type.js
  server/schema/common/userDetail.input.type.js
  server/schema/company/company.datasources.js
  server/schema/company/company.mutation.js
  server/schema/company/company.query.js
  server/schema/company/company.resolver.js
  server/schema/company/company.schema.js
  server/schema/company/company.type.js
  server/schema/index.js
  server/schema/live/live.datasources.js
  server/schema/live/live.model.js
  server/schema/live/live.mutation.js
  server/schema/live/live.query.js
  server/schema/live/live.resolver.js
  server/schema/live/live.schema.js
  server/schema/live/live.type.js
  server/schema/live/student/student.type.js
  server/schema/live/student/studentinfo.input.js
  server/utils/userAuth/index.js
Labels: enhancement, wip
